import { registerCliTests } from "./src/utils/cli_test.ts";
import { registerConfigTests } from "./src/core/config_test.ts";
import { registerFileUtilsTests } from "./src/utils/fileUtils_test.ts";
import { registerFrontmatterTests } from "./src/utils/frontmatter_test.ts";
import { registerTauTests } from "./src/utils/tau_test.ts";
import { registerTauCacheTests } from "./src/utils/tau_cache_test.ts";
import { registerTauConformanceTests } from "./src/utils/tau_conformance_test.ts";
import { registerTauFuzzTests } from "./src/utils/tau_fuzz_test.ts";
import { registerThemeTests } from "./src/theme/theme_test.ts";
import { registerServerTests } from "./src/utils/server_test.ts";
import { registerPublicApiTests } from "./src/public_api_test.ts";
import { registerBuildTests } from "./src/core/build/build_test.ts";
import { registerPluginTests } from "./src/plugins/plugins_test.ts";
import { registerIsolatedPluginTests } from "./src/plugins/isolated_plugin_test.ts";
import { registerCollectionTests } from "./src/core/collections_test.ts";
import { registerProjectTests } from "./src/core/project_test.ts";
import { registerDataTests } from "./src/core/data_test.ts";
import { registerEnvironmentTests } from "./src/core/environment_test.ts";
import { registerHeadTests } from "./src/core/head_test.ts";
import { registerOutputTransactionTests } from "./src/core/build/output_transaction_test.ts";
import { registerPathUtilsTests } from "./src/core/path_utils_test.ts";

registerCliTests();
registerConfigTests();
registerFileUtilsTests();
registerFrontmatterTests();
registerTauTests();
registerTauCacheTests();
registerTauConformanceTests();
registerTauFuzzTests();
registerThemeTests();
registerServerTests();
registerPublicApiTests();
registerBuildTests();
registerPluginTests();
registerIsolatedPluginTests();
registerCollectionTests();
registerProjectTests();
registerDataTests();
registerEnvironmentTests();
registerHeadTests();
registerOutputTransactionTests();
registerPathUtilsTests();
