import { registerCliTests } from "./src/utils/cli_test.ts";
import { registerConfigTests } from "./src/core/config_test.ts";
import { registerFileUtilsTests } from "./src/utils/fileUtils_test.ts";
import { registerFrontmatterTests } from "./src/utils/frontmatter_test.ts";
import { registerScribeTests } from "./src/utils/scribe_test.ts";
import { registerThemeTests } from "./src/theme/theme_test.ts";
import { registerServerTests } from "./src/utils/server_test.ts";
import { registerPublicApiTests } from "./src/public_api_test.ts";
import { registerBuildTests } from "./src/core/build_test.ts";
import { registerPluginTests } from "./src/plugins/plugins_test.ts";
import { registerCollectionTests } from "./src/core/collections_test.ts";
import { registerProjectTests } from "./src/core/project_test.ts";
import { registerDataTests } from "./src/core/data_test.ts";

registerCliTests();
registerConfigTests();
registerFileUtilsTests();
registerFrontmatterTests();
registerScribeTests();
registerThemeTests();
registerServerTests();
registerPublicApiTests();
registerBuildTests();
registerPluginTests();
registerCollectionTests();
registerProjectTests();
registerDataTests();
