name: Publish

on:
  release:
    types: [published]

jobs:
  quality:
    if: github.event.release.target_commitish == 'main'
    uses: ./.github/workflows/ci.yml

  publish-steno:
    needs: quality
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno publish

  publish-themes:
    needs: publish-steno
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        package:
          - packages/theme-minimal
          - packages/theme-docs-minimal
          - packages/theme-marketing-minimal

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno publish
        working-directory: ${{ matrix.package }}

  publish-init:
    needs: publish-themes
    if: github.event.release.target_commitish == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno publish
        working-directory: packages/init
